CREATE TABLE table_m3 (
    "ID" SERIAL PRIMARY KEY,
	"age" INT,
	"attrition" VARCHAR(100),
	"businessTravel" VARCHAR(100),
	"dailyRate" INT,
	"department" VARCHAR(100),
	"distanceFromHome" INT,
	"education" VARCHAR(100),
	"educationField" VARCHAR(100),
	"employeeCount" INT,
	"environmentSatisfaction" VARCHAR(100),
	"gender" VARCHAR(100),
	"hourlyRate" INT,
	"jobInvolvement" VARCHAR(100),
	"jobLevel" INT,
	"jobRole" VARCHAR(100),
	"jobSatisfaction" VARCHAR(100),
	"maritalStatus" VARCHAR(100),
	"monthlyIncome" INT,
	"monthlyRate" INT,
	"numCompaniesWorked" INT,
	"over18" VARCHAR(100),
	"overTime" VARCHAR(100),
	"percentSalaryHike" INT,
	"performanceRating" VARCHAR(100),
	"relationshipSatisfaction" VARCHAR(100),
	"standardHours" INT,
	"stockOptionLevel" INT,
	"totalWorkingYears" INT,
	"trainingTimesLastYear" INT,
	"workLifeBalance" VARCHAR(100),
	"yearsAtCompany" INT,
	"yearsInCurrentRole" INT,
	"yearsSinceLastPromotion" INT,
	"yearsWithCurrManager" INT
);

COPY table_m3("ID", "age", "attrition", "businessTravel", "dailyRate", "department",
       "distanceFromHome", "education", "educationField", "employeeCount",
       "environmentSatisfaction", "gender", "hourlyRate", "jobInvolvement",
       "jobLevel", "jobRole", "jobSatisfaction", "maritalStatus",
       "monthlyIncome", "monthlyRate", "numCompaniesWorked", "over18",
       "overTime", "percentSalaryHike", "performanceRating",
       "relationshipSatisfaction", "standardHours", "stockOptionLevel",
       "totalWorkingYears", "trainingTimesLastYear", "workLifeBalance",
       "yearsAtCompany", "yearsInCurrentRole", "yearsSinceLastPromotion",
       "yearsWithCurrManager")
FROM '/tmp/HR_employee_attrition_dataset.csv'
WITH (
    FORMAT csv,
    HEADER true,
    DELIMITER ','
);